CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS properties (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  price INT NOT NULL,
  price_type VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  featured INT NOT NULL DEFAULT 0,
  location VARCHAR(255) NOT NULL,
  address VARCHAR(500) NOT NULL,
  beds INT NOT NULL,
  baths INT NOT NULL,
  sqft INT NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(1000) NOT NULL,
  images TEXT NOT NULL,
  amenities TEXT NOT NULL
);
